#!/bin/bash
# Made to make git add, commit, push all at once
echo "Git Commit & Github Push Combo"
echo "Enter commit message"
read COM_MES
if test "$COM_MES" != "no"
then
    git add -A
    git commit -m "$COM_MES"
    git push origin master
fi
